query Read($id: UUID!) {
  result: formById(id: $id) {
    ...Form
  }
}

fragment Form on FormGQLModel {
   	__typename
    id
    name
    
    lastchange
    created
    changedby { id name }
    createdby { id name }
   request { id name }
  sections {
    id
    name
    order
    parts {
      id
      name
      order
      items {
        id
        name
        value
        order
        type { id name }
      }
    }
  }
}