query Read($id: UUID!) {
  result: surveyById(id: $id) {
    ...Survey
  }
}

fragment Survey on SurveyGQLModel {
   	__typename
    id
    name
    
    lastchange
    created
    changedby { id name }
    createdby { id name }
   
}