const codes = [
    {"value":"Ing. arch.", "name":  "Ing. arch."},
    {"value":"Dr. Ing.", "name":  "Dr. Ing."},
    {"value":"Ing.", "name":  "Ing."},
    {"value":"Bc.", "name":  "Bc."},
    {"value":"Mgr. art.", "name":  "Mgr. art."},
    {"value":"Mgr.", "name":  "Mgr."},
    {"value":"JUDr.", "name":  "JUDr."},
    {"value":"MUDr.", "name":  "MUDr."},
    {"value":"MVDr.", "name":  "MVDr."},
    {"value":"RNDr.", "name":  "RNDr."},
    {"value":"RSDr.", "name":  "RSDr."},
    {"value":"PhDr.", "name":  "PhDr."},
    {"value":"PhMr.", "name":  "PhMr."},
    {"value":"ThDr.", "name":  "ThDr."},
    {"value":"PaedDr.", "name":  "PaedDr."},
    {"value":"PharmDr.", "name":  "PharmDr."},
    {"value":"MSDr.", "name":  "MSDr."},
    {"value":"MDDr.", "name":  "MDDr."},
    {"value":"Dr. h.c.", "name":  "Dr. h.c."},
    {"value":"PhC.", "name":  "PhC."},
    {"value":"Dr.Sc.", "name":  "Dr.Sc."},
    {"value":"Dr. phil.", "name":  "Dr. phil."},
    {"value":"Dr. habil.", "name":  "Dr. habil."},
    {"value":"akad. arch.", "name":  "akad. arch."},
    {"value":"akad. mal.", "name":  "akad. mal."},
    {"value":"akad. soch.", "name":  "akad. soch."},
    {"value":"arch.", "name":  "arch."},
    {"value":"prom. biol.", "name":  "prom. biol."},
    {"value":"prom. ek.", "name":  "prom. ek."},
    {"value":"prom. filol.", "name":  "prom. filol."},
    {"value":"prom. fil.", "name":  "prom. fil."},
    {"value":"prom. fyz.", "name":  "prom. fyz."},
    {"value":"prom. geol.", "name":  "prom. geol."},
    {"value":"prom. hist.", "name":  "prom. hist."},
    {"value":"prom. mat.", "name":  "prom. mat."},
    {"value":"prom. nov.", "name":  "prom. nov."},
    {"value":"prom. ped.", "name":  "prom. ped."},
    {"value":"prom. psych.", "name":  "prom. psych."},
    {"value":"prom. práv.", "name":  "prom. práv."},
    {"value":"prom. zub.", "name":  "prom. zub."},
    {"value":"prom. pharm.", "name":  "prom. pharm."},
    {"value":"prom. chem.", "name":  "prom. chem."},
    {"value":"prom. geog.", "name":  "prom. geog."},
    {"value":"prom. vet.", "name":  "prom. vet."},
    {"value":"prom. knih.", "name":  "prom. knih."},
    {"value":"prom. učit.", "name":  "prom. učit."},
    {"value":"abs. v.š.", "name":  "abs. v.š."},
    {"value":"h.c.", "name":  "h.c."},
    {"value":"lic.", "name":  "lic."},
    {"value":"Dr. mont.", "name":  "Dr. mont."},
    {"value":"Dr. tech.", "name":  "Dr. tech."},
    {"value":"Baccalaureus", "name":  "Baccalaureus"},
    {"value":"Mag. phil.", "name":  "Mag. phil."},
    {"value":"Th.Lic.", "name":  "Th.Lic."},
    {"value":"ThLic.", "name":  "ThLic."},
    {"value":"MgA.", "name":  "MgA."},
    {"value":"BcA.", "name":  "BcA."},
    {"value":"B. M.", "name":  "B. M."}
]
export const Tituly = ({item, ...rest}) => {
    return (
        <select {...rest} value={item?.value}>
            {codes.map(
                code => <option key={code.value} value={code.value}>{code.name}</option>
            )}            
        </select>
    )
}