
/**
 * Generated filter form for UserInputWhereFilter (for type UserGQLModel).
 * Generated by generate-filter-form.js
 */
import React from "react";

// --- UserInputWhereFilter ---

export function UserInputWhereFilterForm({ value = {}, onChange }) {
    return (
        <div style={{ border: '1px solid #ccc', padding: 8, margin: 8 }}>

            {/* Unhandled type for _or: UserInputWhereFilterOr */}

            {/* Unhandled type for _and: UserInputWhereFilterAnd */}

            <div style={{ marginBottom: 8 }}>
                <label>id:</label>
                <UuidFilterForm value={value.id || {}} onChange={v => onChange({ ...value, id: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>name:</label>
                <StrFilterForm value={value.name || {}} onChange={v => onChange({ ...value, name: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>surname:</label>
                <StrFilterForm value={value.surname || {}} onChange={v => onChange({ ...value, surname: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>email:</label>
                <StrFilterForm value={value.email || {}} onChange={v => onChange({ ...value, email: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>fullname:</label>
                <StrFilterForm value={value.fullname || {}} onChange={v => onChange({ ...value, fullname: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>valid:</label>
                <BoolFilterForm value={value.valid || {}} onChange={v => onChange({ ...value, valid: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>memberships:</label>
                <MembershipInputWhereFilterForm value={value.memberships || {}} onChange={v => onChange({ ...value, memberships: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>roles:</label>
                <RoleInputWhereFilterForm value={value.roles || {}} onChange={v => onChange({ ...value, roles: v })} />
            </div>

        </div>
    );
}
// --- UuidFilter ---

export function UuidFilterForm({ value = {}, onChange }) {
    return (
        <div style={{ border: '1px solid #ccc', padding: 8, margin: 8 }}>

            <div style={{ marginBottom: 8 }}>
                <label>_eq:</label>
                <input
                    type="text"
                    value={value._eq || ""}
                    onChange={e => onChange({ ...value, _eq: e.target.value })}
                />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>_in:</label>
                <input
                    type="text"
                    value={value._in || ""}
                    onChange={e => onChange({ ...value, _in: e.target.value })}
                />
            </div>

        </div>
    );
}
// --- StrFilter ---

export function StrFilterForm({ value = {}, onChange }) {
    return (
        <div style={{ border: '1px solid #ccc', padding: 8, margin: 8 }}>

            <div style={{ marginBottom: 8 }}>
                <label>_eq:</label>
                <input
                    type="text"
                    value={value._eq || ""}
                    onChange={e => onChange({ ...value, _eq: e.target.value })}
                />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>_le:</label>
                <input
                    type="text"
                    value={value._le || ""}
                    onChange={e => onChange({ ...value, _le: e.target.value })}
                />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>_lt:</label>
                <input
                    type="text"
                    value={value._lt || ""}
                    onChange={e => onChange({ ...value, _lt: e.target.value })}
                />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>_ge:</label>
                <input
                    type="text"
                    value={value._ge || ""}
                    onChange={e => onChange({ ...value, _ge: e.target.value })}
                />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>_gt:</label>
                <input
                    type="text"
                    value={value._gt || ""}
                    onChange={e => onChange({ ...value, _gt: e.target.value })}
                />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>_like:</label>
                <input
                    type="text"
                    value={value._like || ""}
                    onChange={e => onChange({ ...value, _like: e.target.value })}
                />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>_ilike:</label>
                <input
                    type="text"
                    value={value._ilike || ""}
                    onChange={e => onChange({ ...value, _ilike: e.target.value })}
                />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>_startswith:</label>
                <input
                    type="text"
                    value={value._startswith || ""}
                    onChange={e => onChange({ ...value, _startswith: e.target.value })}
                />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>_endswith:</label>
                <input
                    type="text"
                    value={value._endswith || ""}
                    onChange={e => onChange({ ...value, _endswith: e.target.value })}
                />
            </div>

        </div>
    );
}
// --- BoolFilter ---

export function BoolFilterForm({ value = {}, onChange }) {
    return (
        <div style={{ border: '1px solid #ccc', padding: 8, margin: 8 }}>

            <div style={{ marginBottom: 8 }}>
                <label>_eq:</label>
                <input
                    type="text"
                    value={value._eq || ""}
                    onChange={e => onChange({ ...value, _eq: e.target.value })}
                />
            </div>

        </div>
    );
}
// --- MembershipInputWhereFilter ---

export function MembershipInputWhereFilterForm({ value = {}, onChange }) {
    return (
        <div style={{ border: '1px solid #ccc', padding: 8, margin: 8 }}>

            {/* Unhandled type for _or: MembershipInputWhereFilterOr */}

            {/* Unhandled type for _and: MembershipInputWhereFilterAnd */}

            <div style={{ marginBottom: 8 }}>
                <label>valid:</label>
                <BoolFilterForm value={value.valid || {}} onChange={v => onChange({ ...value, valid: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>group:</label>
                <GroupInputWhereFilterForm value={value.group || {}} onChange={v => onChange({ ...value, group: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>user:</label>
                <UserInputWhereFilterForm value={value.user || {}} onChange={v => onChange({ ...value, user: v })} />
            </div>

        </div>
    );
}
// --- GroupInputWhereFilter ---

export function GroupInputWhereFilterForm({ value = {}, onChange }) {
    return (
        <div style={{ border: '1px solid #ccc', padding: 8, margin: 8 }}>

            {/* Unhandled type for _or: GroupInputWhereFilterOr */}

            {/* Unhandled type for _and: GroupInputWhereFilterAnd */}

            <div style={{ marginBottom: 8 }}>
                <label>id:</label>
                <UuidFilterForm value={value.id || {}} onChange={v => onChange({ ...value, id: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>name:</label>
                <StrFilterForm value={value.name || {}} onChange={v => onChange({ ...value, name: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>name_en:</label>
                <StrFilterForm value={value.name_en || {}} onChange={v => onChange({ ...value, name_en: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>valid:</label>
                <BoolFilterForm value={value.valid || {}} onChange={v => onChange({ ...value, valid: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>startdate:</label>
                <DatetimeFilterForm value={value.startdate || {}} onChange={v => onChange({ ...value, startdate: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>enddate:</label>
                <DatetimeFilterForm value={value.enddate || {}} onChange={v => onChange({ ...value, enddate: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>grouptype:</label>
                <GroupTypeInputWhereFilterForm value={value.grouptype || {}} onChange={v => onChange({ ...value, grouptype: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>roles:</label>
                <RoleInputWhereFilterForm value={value.roles || {}} onChange={v => onChange({ ...value, roles: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>mastergroup_id:</label>
                <UuidFilterForm value={value.mastergroup_id || {}} onChange={v => onChange({ ...value, mastergroup_id: v })} />
            </div>

        </div>
    );
}
// --- DatetimeFilter ---

export function DatetimeFilterForm({ value = {}, onChange }) {
    return (
        <div style={{ border: '1px solid #ccc', padding: 8, margin: 8 }}>

            <div style={{ marginBottom: 8 }}>
                <label>_eq:</label>
                <input
                    type="text"
                    value={value._eq || ""}
                    onChange={e => onChange({ ...value, _eq: e.target.value })}
                />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>_le:</label>
                <input
                    type="text"
                    value={value._le || ""}
                    onChange={e => onChange({ ...value, _le: e.target.value })}
                />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>_lt:</label>
                <input
                    type="text"
                    value={value._lt || ""}
                    onChange={e => onChange({ ...value, _lt: e.target.value })}
                />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>_ge:</label>
                <input
                    type="text"
                    value={value._ge || ""}
                    onChange={e => onChange({ ...value, _ge: e.target.value })}
                />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>_gt:</label>
                <input
                    type="text"
                    value={value._gt || ""}
                    onChange={e => onChange({ ...value, _gt: e.target.value })}
                />
            </div>

        </div>
    );
}
// --- GroupTypeInputWhereFilter ---

export function GroupTypeInputWhereFilterForm({ value = {}, onChange }) {
    return (
        <div style={{ border: '1px solid #ccc', padding: 8, margin: 8 }}>

            {/* Unhandled type for _or: GroupTypeInputWhereFilterOr */}

            {/* Unhandled type for _and: GroupTypeInputWhereFilterAnd */}

            <div style={{ marginBottom: 8 }}>
                <label>id:</label>
                <UuidFilterForm value={value.id || {}} onChange={v => onChange({ ...value, id: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>name:</label>
                <StrFilterForm value={value.name || {}} onChange={v => onChange({ ...value, name: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>category_id:</label>
                <UuidFilterForm value={value.category_id || {}} onChange={v => onChange({ ...value, category_id: v })} />
            </div>

        </div>
    );
}
// --- RoleInputWhereFilter ---

export function RoleInputWhereFilterForm({ value = {}, onChange }) {
    return (
        <div style={{ border: '1px solid #ccc', padding: 8, margin: 8 }}>

            {/* Unhandled type for _or: RoleInputWhereFilterOr */}

            {/* Unhandled type for _and: RoleInputWhereFilterAnd */}

            <div style={{ marginBottom: 8 }}>
                <label>name:</label>
                <StrFilterForm value={value.name || {}} onChange={v => onChange({ ...value, name: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>valid:</label>
                <BoolFilterForm value={value.valid || {}} onChange={v => onChange({ ...value, valid: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>startdate:</label>
                <DatetimeFilterForm value={value.startdate || {}} onChange={v => onChange({ ...value, startdate: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>enddate:</label>
                <DatetimeFilterForm value={value.enddate || {}} onChange={v => onChange({ ...value, enddate: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>group:</label>
                <GroupInputWhereFilterForm value={value.group || {}} onChange={v => onChange({ ...value, group: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>user:</label>
                <UserInputWhereFilterForm value={value.user || {}} onChange={v => onChange({ ...value, user: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>roletype:</label>
                <RoleTypeInputWhereFilterForm value={value.roletype || {}} onChange={v => onChange({ ...value, roletype: v })} />
            </div>

        </div>
    );
}
// --- RoleTypeInputWhereFilter ---

export function RoleTypeInputWhereFilterForm({ value = {}, onChange }) {
    return (
        <div style={{ border: '1px solid #ccc', padding: 8, margin: 8 }}>

            {/* Unhandled type for _or: RoleTypeInputWhereFilterOr */}

            {/* Unhandled type for _and: RoleTypeInputWhereFilterAnd */}

            <div style={{ marginBottom: 8 }}>
                <label>id:</label>
                <UuidFilterForm value={value.id || {}} onChange={v => onChange({ ...value, id: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>name:</label>
                <StrFilterForm value={value.name || {}} onChange={v => onChange({ ...value, name: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>category:</label>
                <RoleCategoryInputWhereFilterForm value={value.category || {}} onChange={v => onChange({ ...value, category: v })} />
            </div>

        </div>
    );
}
// --- RoleCategoryInputWhereFilter ---

export function RoleCategoryInputWhereFilterForm({ value = {}, onChange }) {
    return (
        <div style={{ border: '1px solid #ccc', padding: 8, margin: 8 }}>

            {/* Unhandled type for _or: RoleCategoryInputWhereFilterOr */}

            {/* Unhandled type for _and: RoleCategoryInputWhereFilterAnd */}

            <div style={{ marginBottom: 8 }}>
                <label>id:</label>
                <UuidFilterForm value={value.id || {}} onChange={v => onChange({ ...value, id: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>name:</label>
                <StrFilterForm value={value.name || {}} onChange={v => onChange({ ...value, name: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>name_en:</label>
                <StrFilterForm value={value.name_en || {}} onChange={v => onChange({ ...value, name_en: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>roletypes:</label>
                <RoleTypeInputWhereFilterForm value={value.roletypes || {}} onChange={v => onChange({ ...value, roletypes: v })} />
            </div>

        </div>
    );
}

/**
 * Example usage:
 * <UserInputWhereFilterForm value={where} onChange={setWhere} />
 */
