query Read($id: UUID!) {
  result: publicationById(id: $id) {
    ...Publication
  }
}

fragment Publication on PublicationGQLModel {
   	__typename
    id
    name
    
    lastchange
    created
    changedby { id name }
    createdby { id name }
   
}