
/**
 * Generated filter form for AdmissionInputFilter (for type AdmissionGQLModel).
 * Generated by generate-filter-form.js
 */
import React from "react";

// --- AdmissionInputFilter ---

export function AdmissionInputFilterForm({ value = {}, onChange }) {
    return (
        <div style={{ border: '1px solid #ccc', padding: 8, margin: 8 }}>

            {/* Unhandled type for _or: AdmissionInputFilter_or */}

            {/* Unhandled type for _and: AdmissionInputFilter_and */}

            <div style={{ marginBottom: 8 }}>
                <label>id:</label>
                <UuidFilterForm value={value.id || {}} onChange={v => onChange({ ...value, id: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>programId:</label>
                <input
                    type="text"
                    value={value.programId || ""}
                    onChange={e => onChange({ ...value, programId: e.target.value })}
                />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>stateId:</label>
                <input
                    type="text"
                    value={value.stateId || ""}
                    onChange={e => onChange({ ...value, stateId: e.target.value })}
                />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>paymentInfoId:</label>
                <input
                    type="text"
                    value={value.paymentInfoId || ""}
                    onChange={e => onChange({ ...value, paymentInfoId: e.target.value })}
                />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>name:</label>
                <StrFilterForm value={value.name || {}} onChange={v => onChange({ ...value, name: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>name_en:</label>
                <StrFilterForm value={value.name_en || {}} onChange={v => onChange({ ...value, name_en: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>application_start_date:</label>
                <DatetimeFilterForm value={value.application_start_date || {}} onChange={v => onChange({ ...value, application_start_date: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>application_last_date:</label>
                <DatetimeFilterForm value={value.application_last_date || {}} onChange={v => onChange({ ...value, application_last_date: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>end_date:</label>
                <DatetimeFilterForm value={value.end_date || {}} onChange={v => onChange({ ...value, end_date: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>condition_date:</label>
                <DatetimeFilterForm value={value.condition_date || {}} onChange={v => onChange({ ...value, condition_date: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>payment_date:</label>
                <DatetimeFilterForm value={value.payment_date || {}} onChange={v => onChange({ ...value, payment_date: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>condition_extended_date:</label>
                <DatetimeFilterForm value={value.condition_extended_date || {}} onChange={v => onChange({ ...value, condition_extended_date: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>request_condition_extend_date:</label>
                <DatetimeFilterForm value={value.request_condition_extend_date || {}} onChange={v => onChange({ ...value, request_condition_extend_date: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>request_extra_conditions_date:</label>
                <DatetimeFilterForm value={value.request_extra_conditions_date || {}} onChange={v => onChange({ ...value, request_extra_conditions_date: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>request_extra_date_date:</label>
                <DatetimeFilterForm value={value.request_extra_date_date || {}} onChange={v => onChange({ ...value, request_extra_date_date: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>exam_start_date:</label>
                <DatetimeFilterForm value={value.exam_start_date || {}} onChange={v => onChange({ ...value, exam_start_date: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>exam_last_date:</label>
                <DatetimeFilterForm value={value.exam_last_date || {}} onChange={v => onChange({ ...value, exam_last_date: v })} />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>student_entry_date:</label>
                <DatetimeFilterForm value={value.student_entry_date || {}} onChange={v => onChange({ ...value, student_entry_date: v })} />
            </div>

            {/* Unhandled type for payment_info: AdmissionInputFilterPaymentInfo */}

        </div>
    );
}
// --- UuidFilter ---

export function UuidFilterForm({ value = {}, onChange }) {
    return (
        <div style={{ border: '1px solid #ccc', padding: 8, margin: 8 }}>

            <div style={{ marginBottom: 8 }}>
                <label>_eq:</label>
                <input
                    type="text"
                    value={value._eq || ""}
                    onChange={e => onChange({ ...value, _eq: e.target.value })}
                />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>_in:</label>
                <input
                    type="text"
                    value={value._in || ""}
                    onChange={e => onChange({ ...value, _in: e.target.value })}
                />
            </div>

        </div>
    );
}
// --- StrFilter ---

export function StrFilterForm({ value = {}, onChange }) {
    return (
        <div style={{ border: '1px solid #ccc', padding: 8, margin: 8 }}>

            <div style={{ marginBottom: 8 }}>
                <label>_eq:</label>
                <input
                    type="text"
                    value={value._eq || ""}
                    onChange={e => onChange({ ...value, _eq: e.target.value })}
                />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>_le:</label>
                <input
                    type="text"
                    value={value._le || ""}
                    onChange={e => onChange({ ...value, _le: e.target.value })}
                />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>_lt:</label>
                <input
                    type="text"
                    value={value._lt || ""}
                    onChange={e => onChange({ ...value, _lt: e.target.value })}
                />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>_ge:</label>
                <input
                    type="text"
                    value={value._ge || ""}
                    onChange={e => onChange({ ...value, _ge: e.target.value })}
                />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>_gt:</label>
                <input
                    type="text"
                    value={value._gt || ""}
                    onChange={e => onChange({ ...value, _gt: e.target.value })}
                />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>_like:</label>
                <input
                    type="text"
                    value={value._like || ""}
                    onChange={e => onChange({ ...value, _like: e.target.value })}
                />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>_ilike:</label>
                <input
                    type="text"
                    value={value._ilike || ""}
                    onChange={e => onChange({ ...value, _ilike: e.target.value })}
                />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>_startswith:</label>
                <input
                    type="text"
                    value={value._startswith || ""}
                    onChange={e => onChange({ ...value, _startswith: e.target.value })}
                />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>_endswith:</label>
                <input
                    type="text"
                    value={value._endswith || ""}
                    onChange={e => onChange({ ...value, _endswith: e.target.value })}
                />
            </div>

        </div>
    );
}
// --- DatetimeFilter ---

export function DatetimeFilterForm({ value = {}, onChange }) {
    return (
        <div style={{ border: '1px solid #ccc', padding: 8, margin: 8 }}>

            <div style={{ marginBottom: 8 }}>
                <label>_eq:</label>
                <input
                    type="text"
                    value={value._eq || ""}
                    onChange={e => onChange({ ...value, _eq: e.target.value })}
                />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>_le:</label>
                <input
                    type="text"
                    value={value._le || ""}
                    onChange={e => onChange({ ...value, _le: e.target.value })}
                />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>_lt:</label>
                <input
                    type="text"
                    value={value._lt || ""}
                    onChange={e => onChange({ ...value, _lt: e.target.value })}
                />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>_ge:</label>
                <input
                    type="text"
                    value={value._ge || ""}
                    onChange={e => onChange({ ...value, _ge: e.target.value })}
                />
            </div>

            <div style={{ marginBottom: 8 }}>
                <label>_gt:</label>
                <input
                    type="text"
                    value={value._gt || ""}
                    onChange={e => onChange({ ...value, _gt: e.target.value })}
                />
            </div>

        </div>
    );
}

/**
 * Example usage:
 * <AdmissionInputFilterForm value={where} onChange={setWhere} />
 */
