/**
 * Generated filter form for AdmissionInputFilter (for type AdmissionGQLModel), Bootstrap styl, single field selection, logická pole.
 * Generated by generate-hasura-filter-form.js
 */
import { SimpleCardCapsule } from "@hrbolek/uoisfrontend-shared";
import React from "react";
import { Col, Row } from "react-bootstrap";
import { Sim } from "react-bootstrap-icons";

const logicalFields = ['_and', '_or'];
const fieldTypes = {
    "id": "String",
    "programId": "UUID",
    "stateId": "UUID",
    "paymentInfoId": "UUID",
    "name": "String",
    "name_en": "String",
    "application_start_date": "String",
    "application_last_date": "String",
    "end_date": "String",
    "condition_date": "String",
    "payment_date": "String",
    "condition_extended_date": "String",
    "request_condition_extend_date": "String",
    "request_extra_conditions_date": "String",
    "request_extra_date_date": "String",
    "exam_start_date": "String",
    "exam_last_date": "String",
    "student_entry_date": "String",
    "payment_info": "String"
};

function getHtmlInputType(scalarType) {
    switch (scalarType) {
        case "String": return "text";
        case "Int": case "BigInt": return "number";
        case "Float": case "Decimal": return "number";
        case "Boolean": return "checkbox";
        case "Date": return "date";
        case "Time": return "time";
        case "DateTime": case "Timestamp": return "datetime-local";
        default: return "text";
    }
}
function getFieldScalarType(fieldName) {
    return fieldTypes[fieldName] || "String";
}

/**
 * @param {object} props
 * @param {object} props.value  Aktuální hodnota filtru (where objekt)
 * @param {function} props.onChange  Callback onChange(newValue)
 * @param {string|null} [props.parentLogical]  Parent logical (pokud je uvnitř _and/_or)
 */
export function AdmissionInputFilterForm({ value = {}, onChange, parentLogical = null }) {
    const activeLogical = Object.keys(value).find(k => logicalFields.includes(k));
    const isLogic = !!activeLogical;
    const scalars = ["id", "programId", "stateId", "paymentInfoId", "name", "name_en", "application_start_date", "application_last_date", "end_date", "condition_date", "payment_date", "condition_extended_date", "request_condition_extend_date", "request_extra_conditions_date", "request_extra_date_date", "exam_start_date", "exam_last_date", "student_entry_date", "payment_info"];
    const logical = logicalFields.filter(x => x !== parentLogical);
    const selectedField = !isLogic ? Object.keys(value).find(k => !k.startsWith("_")) || "" : "";
    const [operand, setOperand] = React.useState(selectedField ? value[selectedField] : "");

    React.useEffect(() => {
        if (selectedField && value[selectedField] !== operand) setOperand(value[selectedField]);
    }, [value, selectedField]);

    function handleFieldChange(e) {
        const f = e.target.value;
        setOperand(""); // Resetovat operand
        onChange({ [f]: "" });
    }
    function handleOperandChange(e) {
        let val = e.target.value;
        if (e.target.type === "checkbox") val = e.target.checked;
        setOperand(val);
        onChange({ [selectedField]: val });
    }
    function handleAddLogical(logicKey) {
        onChange({ [logicKey]: [{}] });
    }
    function handleLogicChange(idx, v) {
        const arr = [...(value[activeLogical] || [])];
        arr[idx] = v;
        onChange({ [activeLogical]: arr });
    }
    return (
        <div>
            <div className="mb-3 d-flex gap-2">
                {!isLogic && logical.length > 0 && (  
                    <div className="mb-3 d-flex gap-2">
                        {logical.map(f => (
                            <button key={f} type="button"
                                className="btn btn-outline-primary form-control"
                                onClick={() => handleAddLogical(f)}
                            >{f.toUpperCase()}</button>
                        ))}
                    </div>
                )}
                {!isLogic && !selectedField && (
                    <SimpleCardCapsule title={"Operátor/field"}>
                        <select className="form-select" value={selectedField} onChange={handleFieldChange}>
                            <option value="">Vyber operátor…</option>
                            {scalars.map(f => <option key={f} value={f}>{f}</option>)}
                        </select>
                    </SimpleCardCapsule>
                )}
                {!isLogic && selectedField && (() => {
                    const scalarType = getFieldScalarType(selectedField);
                    const inputType = getHtmlInputType(scalarType);
                    return (
                        <SimpleCardCapsule title={selectedField.toUpperCase()}>
                            <Row>
                                <Col>
                                    <select className="form-select" value={selectedField} onChange={handleFieldChange}>
                                        <option value="">Vyber operátor…</option>
                                        {scalars.map(f => <option key={f} value={f}>{f}</option>)}
                                    </select>
                                </Col>
                                <Col>
                                    <input
                                        className="form-control"
                                        type={inputType}
                                        value={inputType === "checkbox" ? undefined : operand}
                                        checked={inputType === "checkbox" ? operand || false : undefined}
                                        onChange={handleOperandChange}
                                        placeholder={"Zadej hodnotu"}
                                    />
                                </Col>
                            </Row>
                        </SimpleCardCapsule>
                    );
                })()}
                {isLogic && (
                    <SimpleCardCapsule title={activeLogical.toUpperCase()}>
                        {(value[activeLogical] || []).map((item, idx) => (
                            <AdmissionInputFilterForm
                                key={idx}
                                value={item}
                                onChange={v => handleLogicChange(idx, v)}
                                parentLogical={activeLogical}
                            />
                        ))}
                        <button
                            className="btn btn-outline-primary btn-sm mt-1"
                            type="button"
                            onClick={() => onChange({ ...value, [activeLogical]: [...(value[activeLogical] || []), {}] })}
                        >
                            Přidat podmínku
                        </button>
                    </SimpleCardCapsule>
                )}
            </div>
            <pre>
                {JSON.stringify(value, null, 2)}
            </pre>
            <hr />
        </div>
    );
}

// Example usage:
// <AdmissionInputFilterForm value={where} onChange={setWhere} />

