query Read($id: UUID!) {
  result: requestById(id: $id) {
    id
    name
    createdby {id fullname}
    created
    lastchange
    histories {
      id
      name
      lastchange
      changedby { id fullname }
      form { id name }
    }

    state {
      id name
      targets { id name target { id name }}
      writers: roletypes(access: WRITE) {
        name
      }
      readers: roletypes(access: READ) {
        name
      }
    }    
  }
}