query UserReadEvents($id: UUID!, $skip: Int, $limit: Int, $where: UGEventInputFilter) {
  result: userById(id: $id) {
    ...User
  }
}

fragment User on UserGQLModel {
  __typename
  id
  lastchange
  name
  surname
  fullname
  email
  created
  createdby {
    id
    email
  }
  changedby {
    id
    name
  }
  events(skip: $skip, limit: $limit, where: $where) {
    ...Event
  }
}

fragment Event on EventGQLModel {
	__typename
  id
  lastchange
  name
  nameEn
  startdate
  enddate
  duration
  description
  
  place
  placeId
  
  eventType { id name }
  
  created
  createdby { id email }
  changedby { id email } 
  
  users { id fullname email }
  groups { id name }
  masterEvent { id name }
}