query UserById($id: UUID!) {
  result: userById(id: $id) {
    ...User
  }
}

fragment User on UserGQLModel {
  __typename
  id
  lastchange
  name
  surname
  fullname
  email

  roles {
    __typename
    id
    roletype { id name }
    group { id name }
    valid
    startdate
    enddate
    lastchange
    changedby { id fullname }
  }
  
  membership {
    id
    group { 
      id name 
      grouptype { id name }
    }
    valid
    startdate
    enddate
  }

  created
  createdby {
    id
    email
  }
  changedby {
    id
    name
  }
  rbacobject { id }
}