query Read($id: UUID!) {
  result: facilityById(id: $id) {
    ...Facility
  }
}

fragment Facility on FacilityGQLModel {
   	__typename
    id
    name
    
    lastchange
    created
    changedby { id name }
    createdby { id name }
   
}