query GroupReadEvents($id: UUID!, $skip: Int, $limit: Int, $where: UGEventInputFilter) {
  result: groupById(id: $id) {
    ...Group
  }
}

fragment Group on GroupGQLModel {
	__typename
  id
  lastchange
  name
  nameEn
  abbreviation
  
  created
  createdby { id email }
  changedby { id email }
  
  email
  valid
  events(skip: $skip, limit: $limit, where: $where){
    ...Event
  }
}

fragment Event on EventGQLModel {
	__typename
  id
  lastchange
  name
  nameEn
  startdate
  enddate
  duration
  description
  
  place
  placeId
  
  eventType { id name }
  
  created
  createdby { id email }
  changedby { id email } 
  
  users { id fullname email }
  groups { id name }
  masterEvent { id name }
}