query GroupById($id: UUID!) {
  result: groupById(id: $id) {
    ...Group
  }
}

fragment Group on GroupGQLModel {
	__typename
  id
  lastchange
  name
  nameEn
  abbreviation
  
  created
  createdby { id email }
  changedby { id email }
  
  email
  valid
  grouptype { id name }
  subgroups { id name valid grouptype { id name } }
  mastergroup { id name }

  memberships {
    id
    lastchange
    startdate
    enddate
    valid
    user { id fullname }
  }

  roles {
    valid
    user { id fullname }
    roletype { id name }
  }
}
