query EventPage($skip: Int, $limit: Int, $where: EventInputFilter) {
  result: eventPage(skip: $skip, limit: $limit, where: $where) {
    ...Event
  }
}

fragment Event on EventGQLModel {
	__typename
  id
  lastchange
  name
  nameEn
  startdate
  enddate
  duration
  description
  
  eventType { id name }
  
  created
  createdby { id email }
  changedby { id email }
  
  
  subEvents { id name }
  masterEvent { id name }
}
