query ($id: UUID!) {
    result: eventById(id: $id) {
          __typename
          id
          lastchange
          name
          startdate
          enddate
          eventType {
            id
            name
          }
      }
     }