query ($id: UUID!) {
    result: eventById(id: $id) {
        ...Event
    }
}


fragment Event on EventGQLModel {
	__typename
  id
  lastchange
  name
  nameEn
  startdate
  enddate
  duration
  description
  
  eventType { id name }
  
  created
  createdby { id email }
  changedby { id email }
  
  
  subEvents { id name }
  masterEvent { id name }
}
