mutation EventUpdate($id: UUID!, $lastchange: DateTime! $type_id: UUID, $name: String, $startdate: DateTime, $enddate: DateTime) {
  result: eventUpdate(event: {id: $id, lastchange: $lastchange, typeId: $type_id, name: $name, startdate: $startdate, enddate: $enddate}) {
    id
    msg
    result: event {
    	...Event
    }
  }
}

fragment Event on EventGQLModel {
	__typename
  id
  lastchange
  name
  nameEn
  startdate
  enddate
  duration
  description
  
  eventType { id name }
  
  created
  createdby { id email }
  changedby { id email }
  
  
  subEvents { id name }
  masterEvent { id name }
}
