query Read($id: UUID!) {
  result: acProgramById(id: $id) {
    ...AcProgram
  }
}

fragment AcProgram on AcProgramGQLModel {
   	__typename
    id
    name
    
    lastchange
    created
    changedby { id name }
    createdby { id name }
   
  type { id name }
  subjects { id name }
  grantsGroup { id name }
  licencedGroup { id name }
  
}