query Read($id: UUID!) {
  result: projectById(id: $id) {
    ...Project
  }
}

fragment Project on ProjectGQLModel {
  __typename
  id

  lastchange
  created
  changedby {
    id
    name
  }
  createdby {
    id
    name
  }
  
  name
	startdate  
  enddate
  valid
  
  finances { id name amount financeType { id name }}
  milestones { id name startdate enddate }
  projectType { id name }
  team { id name }
  group { id name }
}